// Prompt configuration for the chat API route.
// This file has NO React dependencies — safe to import from server-only routes.
//
// Component specs are generated by `pnpm generate:prompt` and imported from the
// generated JSON file. Tools are injected at request time from MCP.

import type { PromptSpec } from "@openuidev/react-lang";
import componentSpec from "./generated/component-spec.json";

export const promptSpec: PromptSpec = {
  ...componentSpec as PromptSpec,
  editMode: true,
  inlineMode: true,
  toolExamples: [
    `Example — Linear issues overview (use real tool names from the injected tool list):
root = Stack([header, tableCard])
header = CardHeader("My issues", "From Linear MCP — adjust Query() name/args to match your workspace tools")
issues = Query("<linear_list_or_search_tool>", { }, { issues: [] })
tableCard = Card([CardHeader("Issues"), Table([Col("Title", issues.issues.title), Col("State", issues.issues.state), Col("Team", issues.issues.team)])])`,

    `Example — Single issue KPIs (shape depends on tool response — use defaults that match the schema):
root = Stack([header, row])
header = CardHeader("Sprint snapshot", "Pull data with Query then bind to cards")
data = Query("<linear_tool_name>", { }, { count: 0, completed: 0 })
row = Stack([c1, c2], "row", "m", "stretch", "start", true)
c1 = Card([TextContent("Open", "small"), TextContent("" + data.count, "large-heavy")])
c2 = Card([TextContent("Done", "small"), TextContent("" + data.completed, "large-heavy")])`,
  ],
  additionalRules: [
    "Tools come from Linear MCP — use the exact tool names and inputSchema from the injected tool list in the system prompt.",
    "Call Query() with arguments that satisfy the Linear tool schema (IDs, filters, team keys, etc.).",
    "Prefer read-only or safe operations unless the user explicitly asks to create or update Linear data.",
    "If a tool returns nested objects or arrays, align Table/Chart column paths with the actual response shape.",
  ],
  preamble: `You are an AI assistant that builds dashboards using openui-lang, a declarative UI language.

## Linear MCP

Workspace data is provided by **Linear's hosted MCP** (issues, projects, teams, comments, and related operations). Tool names and parameters are listed in the system prompt — follow them exactly when using Query() or Mutation().`,
};
