"use client";

import type { PromptOptions } from "@openuidev/react-lang";
import { createLibrary } from "@openuidev/react-lang";

import {
  EmailArticle,
  EmailAvatar,
  EmailAvatarGroup,
  EmailAvatarWithText,
  EmailBentoGrid,
  EmailBentoItem,
  EmailButton,
  EmailCheckoutItem,
  EmailCheckoutTable,
  EmailCodeBlock,
  EmailCodeInline,
  EmailColumn,
  EmailColumns,
  EmailCustomerReview,
  EmailDivider,
  EmailFeatureGrid,
  EmailFeatureItem,
  EmailFeatureList,
  EmailFooterCentered,
  EmailFooterTwoColumn,
  EmailHeaderCenteredNav,
  EmailHeaderSideNav,
  EmailHeaderSocial,
  EmailHeading,
  EmailImage,
  EmailImageGrid,
  EmailLink,
  EmailList,
  EmailListItem,
  EmailMarkdown,
  EmailNavLink,
  EmailNumberedSteps,
  EmailPricingCard,
  EmailPricingFeature,
  EmailProductCard,
  EmailSection,
  EmailSocialIcon,
  EmailStatItem,
  EmailStats,
  EmailStepItem,
  EmailSurveyRating,
  EmailTemplate,
  EmailTestimonial,
  EmailText,
  emailComponentGroups,
  emailExamples,
  emailAdditionalRules,
} from "@openuidev/react-email";

export const emailPromptOptions: PromptOptions = {
  examples: emailExamples,
  additionalRules: emailAdditionalRules,
};

export const emailChatLibrary = createLibrary({
  root: "EmailTemplate",
  componentGroups: emailComponentGroups,
  components: [
    EmailTemplate,
    EmailSection,
    EmailColumns,
    EmailColumn,
    EmailHeaderSideNav,
    EmailHeaderCenteredNav,
    EmailHeaderSocial,
    EmailNavLink,
    EmailSocialIcon,
    EmailFooterCentered,
    EmailFooterTwoColumn,
    EmailHeading,
    EmailText,
    EmailButton,
    EmailImage,
    EmailDivider,
    EmailLink,
    EmailCodeBlock,
    EmailCodeInline,
    EmailMarkdown,
    EmailArticle,
    EmailProductCard,
    EmailFeatureItem,
    EmailFeatureGrid,
    EmailFeatureList,
    EmailStepItem,
    EmailNumberedSteps,
    EmailCheckoutItem,
    EmailCheckoutTable,
    EmailPricingFeature,
    EmailPricingCard,
    EmailTestimonial,
    EmailSurveyRating,
    EmailStatItem,
    EmailStats,
    EmailImageGrid,
    EmailAvatar,
    EmailAvatarGroup,
    EmailAvatarWithText,
    EmailListItem,
    EmailList,
    EmailCustomerReview,
    EmailBentoItem,
    EmailBentoGrid,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ] as any[],
});
