import { createLibrary } from "@openuidev/react-lang";
import { dashboardComponents } from "./defineComponents";

/** Dashboard components and generation guidance, rooted at `Dashboard`. */
export const dashboardComponentGroups = [
  {
    name: "Dashboard Layout",
    components: [
      "Dashboard",
      "DashboardHeader",
      "Section",
      "FilterBar",
      "FilterSelect",
      "FilterMultiSelect",
      "FilterOption",
      "DatePicker",
      "CardRow",
      "IconButton",
    ],
    notes: [
      "Use Dashboard as the dashboard root with DashboardHeader plus Section children.",
      "Use DashboardHeader for the page-level dashboard header.",
      "Use one Section for most dashboard content. Create multiple Sections only for altogether different topics or domains, such as Sales vs Expenses. Do not create a new Section for every row or card.",
      "A Section owns rows and an optional section-scoped FilterBar. Put a FilterBar in the Section whose rows it affects.",
      "FilterBar supports only these filter types: FilterSelect, FilterMultiSelect, and DatePicker with mode single or range. Do not use Select, Input, FormControl, Tabs, MarkDownRenderer, TextContent, TagBlock, or Separator inside FilterBar.",
      'Never pass raw {value, label} object literals as options — always FilterOption children, e.g. FilterSelect("region", "Region", [FilterOption("na", "North America"), FilterOption("emea", "EMEA")], "na").',
      "Use CardRow for horizontal card arrangements inside Section.",
      "Valid CardRow patterns are: small-only, medium-only, medium+large mixed, or large-only.",
    ],
  },
  {
    name: "Shell Cards",
    components: [
      "SmallCard",
      "MediumCard",
      "LargeCard",
      "IconTag",
      "IconText",
      "DashboardCardHeader",
      "TextBlock",
      "List",
      "ListItem",
      "EntityList",
      "Callout",
      "Button",
      "ButtonGroup",
      "Select",
      "SelectItem",
      "ImageBlock",
      "Tag",
      "TagBlock",
      "TextContent",
      "MarkDownRenderer",
      "TextCallout",
    ],
    notes: [
      "SmallCard is compact. MediumCard supports DashboardCardHeader, text, callouts, ImageBlock, charts, tables, lists, actions, tags, and metrics. LargeCard supports the same content as MediumCard except PieChart, donut charts, RadialChart, and RadarChart.",
      "Never place more than one chart inside a MediumCard or LargeCard. If multiple charts are needed, put each chart in its own card.",
      "Use Callout inside MediumCard or LargeCard for info, success, warning, or danger alerts.",
      "Use Button and ButtonGroup inside MediumCard or LargeCard for action triggers. ButtonGroup arranges buttons in a row or column.",
      "Use Select inside MediumCard or LargeCard for inline dropdowns that are not part of the FilterBar filter system.",
      "Use ImageBlock inside MediumCard for displaying images such as logos, product photos, or illustrations.",
      "Use TagBlock with Tag children inside MediumCard or LargeCard for status labels or category chips. Tag variants: success, info, warning, danger, neutral.",
      "Use TextContent for inline markdown text or MarkDownRenderer for full markdown blocks inside MediumCard or LargeCard.",
      "Use TextCallout for a variant-colored callout with title and description. Variants: success, info, warning, danger.",
      "SelectItem is a child of Select. Each SelectItem has a value and label.",
      'Use DashboardCardHeader as the first child inside MediumCard or LargeCard when the card needs title/subtext plus optional compact controls. If a card has a clear leading KPI or score, prefer making that value the DashboardCardHeader title with titleType "number" and use the subtitle for the label; use titleType "text" for descriptive card titles.',
      "Do not use FilterBar, Image, ImageGallery, Separator, CodeBlock, or Form inside MediumCard or LargeCard.",
      "Do not use PieChart, donut charts, RadialChart, or RadarChart inside LargeCard.",
      'When a CardRow contains three MediumCards, or contains a MediumCard alongside a LargeCard, and the MediumCard uses a PieChart or donut chart, always pass appearance "semiCircular" as the SIXTH PieChart argument, padding the interior optionals explicitly, e.g. PieChart(labels, values, "pie", "default", 300, "semiCircular").',
      "Inside LargeCard, use vertical BarChart for categorical comparisons. Do not use HorizontalBarChart in LargeCard unless the user explicitly asks for horizontal bars or the category labels are too long to read on a vertical axis.",
      "MediumCard and LargeCard accept a second positional collapsed boolean. Use collapsed true only for dense cards with multiple body blocks, long text or markdown, or a table with at least 8 rows. Never collapse a card containing only a header and one chart or list, and never collapse a table card with fewer than 8 rows. Use LargeCard(children, true) only when these content rules are met in a mixed MediumCard + LargeCard row; never collapse LargeCard in large-only rows.",
      "SmallCard supports three compact forms: overview card with icon, overview card, and snippet card.",
      "Use overview card with icon as SmallCard(IconText(Icon(...), iconVariant), [MetricIndicator(value, label, trend?)]) when the metric represents a recognizable real-world concept that can be symbolized universally, such as users, revenue, errors, CPU, memory, or latency.",
      "Use overview card as SmallCard(title, metric, trend?) when the metric is abstract, composite, or system-specific and does not have a clear universal visual symbol, such as health score, activation quality, pipeline coverage, or custom internal KPIs.",
      "Use snippet card as SmallCard(lhs, rhs) for compact entity, task, account, alert, or status records where the left side identifies the item and the right side shows one emphasized value/status/time. Do not use snippet cards for top-level aggregate KPI summaries.",
    ],
  },
  {
    name: "Metrics",
    components: ["MetricIndicator", "Trend", "OverviewCardItem", "OverviewCardBlock"],
    notes: [
      "Use MetricIndicator for concise value plus trend callouts inside small, medium, and large cards.",
      "Use OverviewCardBlock for KPI metric grids with OverviewCardItem children.",
      'Never pass raw {direction, value} object literals as a trend argument — always the Trend child, e.g. MetricIndicator("$48.2K", "MRR", Trend("up", 12.5)).',
    ],
  },
  {
    name: "Charts",
    components: [
      "LineChart",
      "BarChart",
      "AreaChart",
      "HorizontalBarChart",
      "RadarChart",
      "ScatterChart",
      "RadialChart",
      "PieChart",
    ],
    notes: [
      "Use LineChart for trends over time.",
      "Use BarChart for comparing values across categories.",
      "Use AreaChart for volume trends with filled area.",
      "Use PieChart for part-to-whole breakdowns. Supports pie, donut, and semiCircular appearance variants.",
      "Use HorizontalBarChart only when category labels are long or the user explicitly requests horizontal bars.",
      "Use RadarChart for multi-factor comparisons across dimensions.",
    ],
  },
  {
    name: "Data Display",
    components: ["Table", "Col"],
    notes: [
      "Use Table with Col children for tabular data. Tables auto-paginate at 10 rows.",
      "Set Col type to 'number' for right-aligned numeric columns.",
    ],
  },
  {
    name: "Primitives",
    components: ["Icon", "IconTag", "IconText", "TextBlock"],
    notes: [
      "Icon takes a name string (e.g. 'dollar-sign', 'users'). Use common lucide icon names.",
    ],
  },
];

export const dashboardLibrary = createLibrary({
  root: "Dashboard",
  components: dashboardComponents,
  componentGroups: dashboardComponentGroups,
});
